05-17 13:58:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:421)
	at com.onseven.dbvis.g.B.C.ā(Z:1315)
	at com.onseven.dbvis.g.B.F$A.call(Z:1369)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
05-17 13:58:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:421)
	at com.onseven.dbvis.g.B.C.ā(Z:1315)
	at com.onseven.dbvis.g.B.F$A.call(Z:1369)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
05-17 13:58:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:421)
	at com.onseven.dbvis.g.B.C.ā(Z:1315)
	at com.onseven.dbvis.g.B.F$A.call(Z:1369)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
